// Knights Stock Control live fixes
(function(){
const BASE='https://jpjrsndbjklecvwiuvbf.supabase.co/rest/v1/stock_products';
const KEY='sb_publishable_3xafRje7lv0WNnV1wkdU4Q_Yo3NYrW7',MEASURE=25;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
let liveProducts=[],livePending=[];
async function api(url,opts={}){const r=await fetch(url,{...opts,headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json',...(opts.headers||{})},cache:'no-store'});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.hint||d||('HTTP '+r.status));return d}
function installLogo(){const h=document.querySelector('.header');if(!h||h.querySelector('.live-brand-logo'))return;const i=document.createElement('img');i.className='live-brand-logo';i.src='logo-exact.svg?v=16';i.alt='Knights Mobile Bars';const b=h.querySelector('.brand');if(b)h.insertBefore(i,b);else h.prepend(i);const st=document.createElement('style');st.textContent='.live-brand-logo{display:block;width:180px;height:180px;object-fit:contain;margin:0 auto 4px}.header{text-align:center}.header .brand{display:none}';document.head.appendChild(st)}
function render(){const rec=liveProducts.reduce((a,p)=>a+Number(p.received||0),0),sold=liveProducts.reduce((a,p)=>a+Number(p.sold||0),0);if($('received'))$('received').textContent=rec;if($('sold'))$('sold').textContent=sold;if($('expected'))$('expected').textContent=rec-sold;if($('count'))$('count').textContent=liveProducts.length;const rows=$('rows');if(!rows)return;rows.innerHTML=liveProducts.length?liveProducts.map(p=>{const r=Number(p.received||0),s=Number(p.sold||0);return `<tr><td>${esc(p.name)}</td><td>${r}</td><td><input class="live-sold" data-id="${esc(p.id)}" type="number" min="0" value="${s}" style="width:75px"></td><td>${r-s}</td><td><button class="secondary live-save" data-id="${esc(p.id)}">Save</button></td></tr>`}).join(''):'<tr><td colspan="5">No stock yet.</td></tr>';rows.onclick=async e=>{if(!e.target.classList.contains('live-save'))return;const id=e.target.dataset.id,v=Math.max(0,Number(rows.querySelector(`.live-sold[data-id="${id}"]`).value)||0);try{await api(BASE+'?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({sold:v})});await window.liveLoad()}catch(err){alert('Could not save stock: '+err.message)}}}
window.liveLoad=async function(){installLogo();const st=$('connection');if(st)st.textContent='Connecting to shared stock…';try{liveProducts=await api(BASE+'?select=*&order=name');window.products=liveProducts;window.liveProducts=liveProducts;if(st)st.textContent='✓ Shared stock connected ('+liveProducts.length+' products)';render()}catch(e){if(st)st.textContent='Database connection failed: '+e.message;console.error(e)}};
function spirit(s){return /\b(gin|vodka|whisk(?:y|e)y|whisky|rum|brandy|cognac|tequila|mezcal|liqueur|disaronno|baileys|amaretto|sambuca|malibu|jack daniel|jameson|smirnoff|gordon'?s|bacardi|captain morgan|absolut|bombay|tanqueray|hendrick|grey goose|ketel one)\b/i.test(s)}
function ml(s){let m=String(s).match(/(\d+(?:\.\d+)?)\s*(ml|cl)\b/i);if(m)return Math.round(Number(m[1])*(m[2].toLowerCase()==='cl'?10:1));m=String(s).match(/(\d+(?:\.\d+)?)\s*(litre|liter|l)\b/i);return m?Math.round(Number(m[1])*1000):null}
function parseLWC(text){const s=String(text).replace(/\u00a0/g,' ').replace(/[\r\n]+/g,' ').replace(/\s+/g,' ').trim(),re=/(\d{7,9})\s+(.+?)\s+(\d{2}\/\d{2}\/\d{4})\s+(\d+)\s+Placed\s+£\s*\d+(?:\.\d{2})\s+(\d+)\s+£\s*\d+(?:\.\d{2})/gi,items=[];let m;while((m=re.exec(s))){const name=m[2].trim(),qty=Number(m[5])||1,pack=name.match(/\b(\d+)\s*[x×]\s*(\d+(?:\.\d+)?)\s*(ml|cl|l)\b/i),keg=name.match(/\b(\d+(?:\.\d+)?)\s*l\s*keg\b/i);let units=qty,sizeText='unit',type='unit';if(pack){units=qty*Number(pack[1]);sizeText=`${pack[1]} x ${pack[2]}${pack[3]}`}else if(keg){type='keg';sizeText=`${keg[1]}L keg`}items.push({name,type,qty,units,sizeText,ref:m[1]})}return items}
function parseBooker(text){const s=String(text).replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim(),re=/(\d{5,})\s+(.+?)\s+(\d+)\s*[x×]?\s*(\d+(?:\.\d+)?)\s*(ml|cl|l)\s+(?:NRB\s+)?\d{2}\/\d{2}\/\d{4}/ig,items=[];let m;while((m=re.exec(s))){const name=m[2].trim(),pack=Number(m[3])||1,v=ml(m[4]+m[5]);items.push(spirit(name)?{name,type:'spirit',qty:1,bottleMl:v,units:v?Math.round(v/MEASURE):0,sizeText:v?v+'ml bottle':'SIZE REQUIRED'}:{name,type:'unit',qty:1,units:pack,sizeText:'pack '+pack})}return items}
function generic(text){const lines=String(text).replace(/\r/g,'').split(/\n/).map(x=>x.trim()).filter(Boolean),out=[];for(let i=0;i<lines.length;i++){let m=lines[i].match(/^(\d{1,3})\s+(.+?)\s+£\s*\d+(?:\.\d{1,2})?/);if(!m)continue;const qty=Number(m[1]),name=m[2].trim(),full=name+' '+lines.slice(i+1,i+3).join(' ');if(spirit(full)){const v=ml(full);out.push({name,type:'spirit',qty,bottleMl:v,units:v?Math.round(v/MEASURE*qty):0,sizeText:v?v+'ml bottle':'SIZE REQUIRED'})}else{const pm=full.match(/(\d+)\s*[x×]/i),pack=pm?Number(pm[1]):1;out.push({name,type:'unit',qty,units:qty*pack,sizeText:pack>1?'pack '+pack:'unit'})}}return out}
function loadScript(src,name){return new Promise((res,rej)=>{if(window[name])return res(window[name]);const s=document.createElement('script');s.src=src;s.onload=()=>window[name]?res(window[name]):rej(Error(name+' unavailable'));s.onerror=()=>rej(Error('Could not load '+src));document.head.appendChild(s)})}
async function pdfText(file){const lib=await loadScript('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js','pdfjsLib');const pdf=await lib.getDocument({data:new Uint8Array(await file.arrayBuffer()),disableWorker:true}).promise;let out='';for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),c=await page.getTextContent({normalizeWhitespace:true}),a=c.items||[];out+='\n'+a.map(x=>x.str).join(' ')}return out}
async function ocr(file){const lib=window.pdfjsLib||await loadScript('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js','pdfjsLib'),ocrLib=await loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js','Tesseract'),pdf=await lib.getDocument({data:new Uint8Array(await file.arrayBuffer()),disableWorker:true}).promise;let out='';for(let p=1;p<=Math.min(pdf.numPages,10);p++){if($('status'))$('status').textContent=`OCR page ${p} of ${pdf.numPages}…`;const page=await pdf.getPage(p),vp=page.getViewport({scale:2}),c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);await page.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;out+='\n'+(await ocrLib.recognize(c,'eng')).data.text}return out}
function parse(text){let items=[];if(/Part\s*Number/i.test(text)&&/Delivery\s*Date/i.test(text)&&/Placed/i.test(text))items=parseLWC(text);if(!items.length&&/Booker/i.test(text))items=parseBooker(text);if(!items.length)items=generic(text);return{supplier:/Booker/i.test(text)?'Booker':/Tesco/i.test(text)?'Tesco':/Part\s*Number/i.test(text)?'LWC':'Invoice / receipt',items}}
function review(items,file){livePending=items;$('supplier').textContent=parse(file.__text||'').supplier+' · '+file.name;$('reviewMsg').textContent=items.length?items.length+' stock lines found. Check quantities before confirming.':'No stock lines could be identified.';$('detected').innerHTML=items.map((x,i)=>`<tr><td><input class="live-nm" data-i="${i}" value="${esc(x.name)}"></td><td>${x.type}</td><td><input class="live-qt" data-i="${i}" type="number" value="${x.qty}" min="0" style="width:65px"></td><td>${x.type==='spirit'?`<input class="live-sz" data-i="${i}" type="number" value="${x.bottleMl||''}" placeholder="ml" style="width:80px"> ml`:esc(x.sizeText||'unit')}</td><td class="live-u" data-i="${i}">${x.type==='spirit'?(x.units?x.units+' shots':'SIZE REQUIRED'):(x.units+' units')}</td></tr>`).join('');$('detected').oninput=e=>{const x=livePending[Number(e.target.dataset.i)];if(!x)return;if(e.target.classList.contains('live-nm'))x.name=e.target.value;if(e.target.classList.contains('live-qt'))x.qty=Number(e.target.value)||0;if(e.target.classList.contains('live-sz'))x.bottleMl=Number(e.target.value)||0;if(x.type==='spirit')x.units=x.bottleMl?Math.round(x.bottleMl/MEASURE*x.qty):0};$('modal').style.display='flex'}
function hook(){const f=$('file');if(f&&!f.dataset.fix){f.dataset.fix='1';f.onchange=async()=>{const file=f.files[0];if(!file)return;try{$('status').textContent='Reading '+file.name+'…';let text=file.type==='application/pdf'||/\.pdf$/i.test(file.name)?await pdfText(file):'';if(text.replace(/\s/g,'').length<40){$('status').textContent='Scanning PDF…';text=await ocr(file)}const parsed=parse(text);file.__text=text;if(!parsed.items.length)throw Error('No stock lines could be identified from this document.');review(parsed.items,file)}catch(e){$('status').textContent='Could not read this file: '+e.message;alert('Could not read the invoice. '+e.message)}}}const c=$('confirm');if(c&&!c.dataset.fix){c.dataset.fix='1';c.onclick=async()=>{for(const x of livePending)if(x.type==='spirit'&&!x.bottleMl)return alert('Enter bottle size for '+x.name);c.disabled=true;try{for(const x of livePending){const units=Number(x.units)||0;if(!units)continue;const ex=liveProducts.find(p=>String(p.name||'').trim().toLowerCase()===String(x.name).trim().toLowerCase());if(ex)await api(BASE+'?id=eq.'+encodeURIComponent(ex.id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({received:Number(ex.received||0)+units})});else await api(BASE,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({name:String(x.name).trim(),received:units,sold:0,low_stock_level:0})})}$('modal').style.display='none';$('status').textContent='✓ Stock added successfully.';livePending=[];await window.liveLoad()}catch(e){alert('Could not add stock: '+e.message)}finally{c.disabled=false}}}}
function loadItemsFix(){const s=document.createElement('script');s.src='fix-items.js?v=1';document.head.appendChild(s)}
function start(){installLogo();hook();window.liveLoad();loadItemsFix()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();