// Knights Stock Control - Items Report + shortages restoration
(function(){
  const BASE='https://jpjrsndbjklecvwiuvbf.supabase.co/rest/v1/stock_products';
  const KEY='sb_publishable_3xafRje7lv0WNnV1wkdU4Q_Yo3NYrW7';
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const api=async(url,opts={})=>{const r=await fetch(url,{...opts,headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json',...(opts.headers||{})},cache:'no-store'});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.hint||d||('HTTP '+r.status));return d};
  let reportRows=[],reportMatches=[],reportPending=[];
  function addStyle(){if($('itemsFixStyle'))return;const s=document.createElement('style');s.id='itemsFixStyle';s.textContent='.shortage-card{background:#fff0ed!important;border-color:#e5b4aa!important}.shortage-list{margin-top:10px}.shortage-row{display:flex;justify-content:space-between;gap:10px;padding:9px 0;border-bottom:1px solid #eee}.report-table{max-height:55vh;overflow:auto}.report-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:12px 0}@media(max-width:700px){.report-summary{grid-template-columns:1fr}}';document.head.appendChild(s)}
  function installTab(){addStyle();const nav=document.querySelector('.nav');if(!nav||document.querySelector('[data-tab="report"]'))return;const b=document.createElement('button');b.dataset.tab='report';b.textContent='Items Report';nav.appendChild(b);const sec=document.createElement('section');sec.id='report';sec.className='hidden';sec.innerHTML='<h2>Items Report</h2><p class="muted">Upload the SumUp Items Report CSV. Nothing changes until you review and confirm.</p><div class="panel"><label class="upload">📊 Upload Items Report (CSV)<input id="reportFile" type="file" accept=".csv,text/csv"></label><div id="reportStatus" class="muted" style="margin-top:10px">No report selected.</div></div><div id="reportReview"></div>';document.getElementById('app').appendChild(sec);b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('#app section').forEach(x=>x.classList.add('hidden'));sec.classList.remove('hidden')};$('reportFile').onchange=handleReport}
  function csv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}if(!rows.length)return[];const head=rows[0].map(x=>x.trim().toLowerCase());return rows.slice(1).map(r=>Object.fromEntries(head.map((h,i)=>[h,(r[i]||'').trim()])))}
  function n(s){const v=String(s||'').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return v?Number(v[0]):0}
  function measure(item,variant){const s=(item+' '+variant).toLowerCase();if(/50\s*ml|double/.test(s))return 2;if(/25\s*ml|single/.test(s))return 1;if(/half\s*pint|\b1\/2\b/.test(s))return 0.5;if(/pint/.test(s))return 1;if(/baby\s*bottle/.test(s))return 1;return 1}
  function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\b(25|50)ml\b/g,'').replace(/\bdouble\b/g,'').trim()}
  function makeReview(rows,products){reportRows=rows;reportMatches=rows.map(r=>{const item=r['item name']||r['item']||'';const variant=r['variant name']||r['variant']||'';const qty=n(r['quantity']);const factor=measure(item,variant);const target=norm(item);let p=products.find(x=>norm(x.name)===target)||products.find(x=>{const a=norm(x.name);return a&&target&&(a.includes(target)||target.includes(a))});return {item,variant,qty,factor,sold:qty*factor,product:p,status:p?'Matched':'Needs review'}});const matched=reportMatches.filter(x=>x.product).reduce((a,x)=>a+x.sold,0),unmatched=reportMatches.filter(x=>!x.product).length;reportPending=reportMatches;const box=$('reportReview');box.innerHTML='<div class="panel"><b>Review Items Report</b><div class="report-summary"><div class="card"><div class="label">Report rows</div><div class="value">'+rows.length+'</div></div><div class="card"><div class="label">Matched sales</div><div class="value">'+matched+'</div></div><div class="card"><div class="label">Needs review</div><div class="value">'+unmatched+'</div></div></div><div class="report-table"><table><thead><tr><th>Item</th><th>Variant</th><th>Qty</th><th>Stock sold</th><th>Match</th></tr></thead><tbody>'+reportMatches.map((x,i)=>'<tr><td>'+esc(x.item)+'</td><td>'+esc(x.variant)+'</td><td>'+x.qty+'</td><td>'+x.sold+'</td><td>'+esc(x.product?.name||'Needs review')+'</td></tr>').join('')+'</tbody></table></div><div class="actions"><button class="secondary" id="reportCancel">Cancel</button><button class="primary" id="reportConfirm" '+(unmatched?'disabled':'')+'>Confirm Sales</button></div></div>';if(unmatched)$('reportStatus').textContent=unmatched+' report lines could not be matched. Nothing will be changed until all lines are reviewed.';else $('reportStatus').textContent='All '+rows.length+' report lines matched. Review then confirm.';$('reportCancel').onclick=()=>box.innerHTML='';$('reportConfirm').onclick=confirmReport}
  async function handleReport(){const f=$('reportFile').files[0];if(!f)return;$('reportStatus').textContent='Reading '+f.name+'…';try{const rows=csv(await f.text());if(!rows.length)throw new Error('CSV contains no rows');const products=await api(BASE+'?select=*&order=name');makeReview(rows,products)}catch(e){$('reportStatus').textContent='Could not read the report: '+e.message}}
  async function confirmReport(){const btn=$('reportConfirm');btn.disabled=true;try{const products=await api(BASE+'?select=*&order=name');const sums=new Map();for(const x of reportPending){if(!x.product)continue;sums.set(x.product.id,(sums.get(x.product.id)||0)+x.sold)}for(const [id,add] of sums){const p=products.find(x=>x.id===id);const sold=Number(p.sold||0)+add;await api(BASE+'?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({sold})})}$('reportReview').innerHTML='<div class="panel"><b>✓ Sales report confirmed.</b><p class="muted">Stock has been updated and the dashboard will refresh.</p></div>';$('reportStatus').textContent='Sales imported successfully.';if(window.liveLoad)await window.liveLoad();else location.reload()}catch(e){alert('Could not save the sales report: '+e.message);btn.disabled=false}}
  function shortages(){const ps=window.liveProducts||window.products||[];const bad=ps.filter(p=>Number(p.received||0)-Number(p.sold||0)<0);let panel=document.querySelector('#dashboard .shortage-panel');if(!panel){panel=document.createElement('div');panel.className='panel shortage-panel';panel.style.marginTop='12px';document.querySelector('#dashboard').appendChild(panel)}panel.classList.toggle('shortage-card',bad.length>0);panel.innerHTML='<b>Stock shortages</b>'+(!bad.length?'<p class="muted">No stock shortages.</p>':'<div class="shortage-list">'+bad.map(p=>'<div class="shortage-row"><span>'+esc(p.name)+'</span><b>'+((Number(p.received||0)-Number(p.sold||0)))+'</b></div>').join('')+'</div>')}
  function wrapLoad(){const old=window.liveLoad;window.liveLoad=async function(){if(old)await old();shortages()};setTimeout(()=>shortages(),1500)}
  function init(){installTab();wrapLoad();shortages()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
