// Knights Stock Control UI restoration: Items Report + dashboard shortages + exact branding
(function(){
  const SUPA_URL='https://jpjrsndbjklecvwiuvbf.supabase.co';
  const SUPA_KEY='sb_publishable_3xafRje7lv0WNnV1wkdU4Q_Yo3NYrW7';
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  let uiProducts=[];
  function style(){if(document.getElementById('ks-ui-fix-style'))return;const s=document.createElement('style');s.id='ks-ui-fix-style';s.textContent='.ks-brand{display:flex;align-items:center;gap:14px}.ks-brand img{width:86px;height:86px;object-fit:contain;background:#fff;border-radius:12px;padding:5px}.ks-brand-title{font:28px Georgia,serif;color:#fff}.ks-brand-sub{color:#bbb;font-size:12px;margin-top:3px}.ks-shortage-card{border:2px solid #e5b4aa}.ks-shortage-card .value{color:#b6403b}.ks-shortage-panel{margin-top:12px}.ks-shortage-row{display:flex;justify-content:space-between;gap:15px;padding:10px 0;border-bottom:1px solid #eee}.ks-shortage-row:last-child{border-bottom:0}.ks-bad{color:#b6403b;font-weight:800}.ks-report-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.ks-report-drop{display:block;background:#111;color:#fff;text-align:center;border-radius:11px;padding:14px;font-weight:700;cursor:pointer}.ks-report-actions{display:flex;gap:10px;justify-content:flex-end;margin-top:12px}.ks-review{position:fixed;inset:0;background:#0008;z-index:50;display:none;align-items:center;justify-content:center;padding:14px}.ks-review-box{background:#f5f2ed;border-radius:18px;max-width:1000px;width:100%;max-height:92vh;overflow:auto;padding:18px}.ks-match-ok{color:#26734d;font-weight:700}.ks-match-bad{color:#b6403b;font-weight:700}@media(max-width:700px){.ks-report-grid{grid-template-columns:1fr}.ks-brand img{width:70px;height:70px}.ks-brand-title{font-size:23px}}';document.head.appendChild(s)}
  function branding(){const h=document.querySelector('.header');if(!h||h.querySelector('.ks-brand'))return;h.innerHTML='<div class="ks-brand"><img src="logo-exact.svg?v=16" alt="Knights Mobile Bars"><div><div class="ks-brand-title">Knights Mobile Bars</div><div class="ks-brand-sub">STOCK CONTROL · SHARED</div></div></div>'}
  function addNav(){const nav=document.querySelector('.nav');if(!nav||nav.querySelector('[data-tab="items-report"]'))return;const b=document.createElement('button');b.type='button';b.dataset.tab='items-report';b.textContent='Items Report';b.onclick=()=>showTab('items-report',b);nav.insertBefore(b,nav.querySelector('[data-tab="take"]')||null)}
  function showTab(id,btn){document.querySelectorAll('#app section').forEach(s=>s.classList.add('hidden'));const sec=document.getElementById(id);if(sec)sec.classList.remove('hidden');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active')}
  function addSection(){if(document.getElementById('items-report'))return;const add=document.getElementById('add');if(!add)return;const sec=document.createElement('section');sec.id='items-report';sec.className='hidden';sec.innerHTML='<h2>Items Report</h2><p class="muted">Upload the items / sales report from your till. KnightsStock will read the products and quantities sold, show you a review, then add the sales to shared stock.</p><div class="panel"><div class="ks-report-grid"><div><label class="ks-report-drop">📄 Upload Items Report<input id="ksItemsFile" type="file" accept=".csv,.txt,.pdf,application/pdf,text/csv" style="display:none"></label><div id="ksItemsStatus" class="muted" style="margin-top:10px">No report selected.</div></div><div class="panel" style="margin:0;background:#faf8f4"><b>Before stock changes</b><p class="muted" style="margin-bottom:0">Nothing is added to Sold until you press <b>Confirm Sales</b>. Unmatched products are flagged for review.</p></div></div></div><div class="panel" style="margin-top:12px"><h3 style="margin-top:0">Recent report</h3><div id="ksReportResult" class="muted">Upload a report to begin.</div></div>';add.parentNode.insertBefore(sec,add.nextSibling);document.getElementById('ksItemsFile').onchange=e=>processReport(e.target.files[0])}
  function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='\"'){if(q&&n==='\"'){cell+='\"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(x=>x.trim()))rows.push(row);row=[]}else cell+=c}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}
  function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
  function findCol(headers,words){return headers.findIndex(h=>words.some(w=>norm(h).includes(w)))}
  function parseSalesText(text){const rows=parseCsv(text);if(rows.length<2)return [];const h=rows[0];const nameI=findCol(h,['product','item','description','name','menu item']);const qtyI=findCol(h,['quantity','qty','units','sold','count']);if(nameI<0||qtyI<0)return [];const map=new Map();for(const r of rows.slice(1)){const name=String(r[nameI]||'').trim();const qty=Number(String(r[qtyI]||'').replace(/[^0-9.-]/g,''));if(name&&Number.isFinite(qty)&&qty!==0){const k=norm(name);map.set(k,{name,qty:(map.get(k)?.qty||0)+qty})}}return [...map.values()]}
  function simpleTextLines(text){const out=[];for(const line of String(text).split(/\r?\n/)){const l=line.trim();if(!l)continue;let m=l.match(/^(.+?)[,\t|]+(\d+(?:\.\d+)?)\s*$/);if(!m)m=l.match(/^(\d+(?:\.\d+)?)\s*[x×]\s*(.+)$/);if(m){const name=/^\d/.test(m[1])?m[2]:m[1],qty=/^\d/.test(m[1])?Number(m[1]):Number(m[2]);if(name&&qty)out.push({name:name.trim(),qty})}}return out}
  async function pdfText(file){if(!window.pdfjsLib){const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';document.head.appendChild(s);await new Promise((res,rej)=>{s.onload=res;s.onerror=rej})}const pdf=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer()),disableWorker:true}).promise;let out='';for(let p=1;p<=Math.min(pdf.numPages,12);p++){const page=await pdf.getPage(p),c=await page.getTextContent();out+='\n'+c.items.map(x=>x.str).join(' ')}return out}
  async function processReport(file){if(!file)return;const status=document.getElementById('ksItemsStatus');status.textContent='Reading '+file.name+'…';let items=[];try{const isPdf=file.type==='application/pdf'||/\.pdf$/i.test(file.name);const text=isPdf?await pdfText(file):await file.text();items=isPdf?simpleTextLines(text):parseSalesText(text);if(!items.length)throw new Error('No product and quantity columns could be identified. CSV should contain a product/item/description column and a quantity/qty column.');showReview(items,file.name)}catch(e){status.textContent='Could not read '+file.name;alert('Could not read the items report. '+e.message)}}
  function showReview(items,fileName){let m=document.getElementById('ksReview');if(!m){m=document.createElement('div');m.id='ksReview';m.className='ks-review';document.body.appendChild(m)}uiProducts=window.liveProducts||[];const rows=items.map((x,i)=>{const p=uiProducts.find(p=>norm(p.name)===norm(x.name))||uiProducts.find(p=>norm(p.name).includes(norm(x.name))||norm(x.name).includes(norm(p.name)));return '<tr><td>'+esc(x.name)+'</td><td><input data-i="'+i+'" class="ks-qty" type="number" min="0" value="'+x.qty+'" style="width:80px"></td><td>'+(p?'<span class="ks-match-ok">Matched: '+esc(p.name)+'</span>':'<span class="ks-match-bad">Not matched</span>')+'</td></tr>'}).join('');m.innerHTML='<div class="ks-review-box"><h2 style="margin-top:0">Review items sold</h2><div class="muted">'+esc(fileName)+'</div><p>Check the quantities. Nothing changes until you confirm.</p><div style="overflow:auto"><table><thead><tr><th>Product in report</th><th>Qty sold</th><th>Stock match</th></tr></thead><tbody>'+rows+'</tbody></table></div><div class="ks-report-actions"><button class="secondary" id="ksCancel">Cancel</button><button class="primary" id="ksConfirm">Confirm Sales</button></div></div>';m.style.display='flex';m.querySelector('#ksCancel').onclick=()=>m.style.display='none';m.querySelector('#ksConfirm').onclick=async()=>{const btn=m.querySelector('#ksConfirm');btn.disabled=true;try{for(let i=0;i<items.length;i++){const qty=Number(m.querySelector('.ks-qty[data-i="'+i+'"]').value)||0;const x=items[i];const p=uiProducts.find(p=>norm(p.name)===norm(x.name))||uiProducts.find(p=>norm(p.name).includes(norm(x.name))||norm(x.name).includes(norm(p.name)));if(!p||!qty)continue;const r=await fetch(SUPA_URL+'/rest/v1/stock_products?id=eq.'+encodeURIComponent(p.id),{method:'PATCH',headers:{apikey:SUPA_KEY,Authorization:'Bearer '+SUPA_KEY,'Content-Type':'application/json','Prefer':'return=minimal'},body:JSON.stringify({sold:Number(p.sold||0)+qty,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error(await r.text())}m.style.display='none';document.getElementById('ksItemsStatus').textContent='✓ Sales confirmed from '+fileName;location.reload()}catch(e){btn.disabled=false;alert('Could not save the sales: '+e.message)}}}
  function dashboardShortages(){const dash=document.getElementById('dashboard');if(!dash)return;const cards=dash.querySelector('.cards');if(cards&&!cards.querySelector('.ks-shortage-card')){const c=document.createElement('div');c.className='card ks-shortage-card';c.innerHTML='<div class="label">Stock shortages</div><div id="ksShortageCount" class="value">0</div><div class="sub">below zero expected</div>';cards.appendChild(c)}if(!dash.querySelector('.ks-shortage-panel')){const p=document.createElement('div');p.className='panel ks-shortage-panel';p.innerHTML='<h3 style="margin-top:0">Stock shortages</h3><div id="ksShortageList" class="muted">No shortages recorded.</div>';dash.appendChild(p)}}
  async function loadShortages(){try{const r=await fetch(SUPA_URL+'/rest/v1/stock_products?select=id,name,received,sold,low_stock_level&order=name',{headers:{apikey:SUPA_KEY,Authorization:'Bearer '+SUPA_KEY},cache:'no-store'});if(!r.ok)return;const ps=await r.json();const bad=ps.filter(p=>Number(p.received||0)-Number(p.sold||0)<0);const c=document.getElementById('ksShortageCount'),list=document.getElementById('ksShortageList');if(c)c.textContent=bad.length;if(list)list.innerHTML=bad.length?bad.map(p=>'<div class="ks-shortage-row"><span><b>'+esc(p.name)+'</b><br><span class="muted">Expected '+(Number(p.received||0)-Number(p.sold||0))+'</span></span><span class="ks-bad">'+(Number(p.received||0)-Number(p.sold||0))+'</span></div>').join(''):'<span class="ks-match-ok">✓ No stock is currently below zero.</span>'}catch(e){console.warn(e)}}
  function init(){style();branding();addNav();addSection();dashboardShortages();loadShortages()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();setTimeout(init,1000);setTimeout(loadShortages,2500);
})();